### ISSUE TITLE
FLASK 

### ISSUE THREAD

**Issue by arinapo** [sid027/dt1-23#13]
Good afternoon,

I have been trying to run the bubble application chat, and I have been constantly receiving the issues. I have tried to fix it by different ways, but none of them seemed to work. I assume it is a flask application that is not running on my VM. Could you please assist me on this point? P.S: All security settings are enabled 
<img width="1435" alt="Screenshot 2023-11-14 at 16 03 29" src="https://github.com/sid027/dt1-23/assets/149295353/8ea9cda4-07b4-463a-9342-69255b524d51">

**Comment by sid027** [comment]
#10

**Comment by sid027** [comment]
related #10

**Comment by sid027** [comment]
the flask application allows CORS so the backend should not be the problem here.
- try to open this Bubble on your phone browser and see if it works there.
- does curl from terminal work fine?

**Comment by joshlevent** [comment]
Check the port number perhaps. "err::connection refused" suggests that the server is denying the request because of a firewall config.

**Comment by joshlevent** [comment]
Sid just tested your server and it looks like the docker is crashing. You’ll need to fix something in the docker.

Here is the error message. The last part indicates that the output from the hugging face model is “null” which is not being handled well. Actually it sort of doesn’t matter, because as long as you didn’t change the docker code, there is something wrong with the way the docker is deployed. You may need to try deploying the docker from scratch.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/main.py", line 25, in call_huggingface_chat_model
    "inputs": f'{questions.replace("_"," ")}',
AttributeError: 'NoneType' object has no attribute ‘replace’
```
When you deploy your docker again, test it first using curl, before attempting to connect to it from the front-end.

**Comment by arinapo** [comment]
@sid027 @joshlevent thanks it helped!
